spring.application.name=codeandevolve
server.port=8888

spring.datasource.url=jdbc:h2:mem:codeandevolve
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
logging.level.org.hibernate.SQL=ERROR
spring.output.ansi.enabled=ALWAYS

logging.level.root=info
logging.pattern.console=%green(%d{yyyy-MM-dd HH:mm:ss}) %red([%thread]) %blue(%-5level) %yellow(%logger{36}) - %msg%n
logging.level.org.springframework.security=TRACE


